name 'netmanagers-ddclient'
version '1.0.5'

author 'Javier Bertoli'
license 'Apache2'
project_page 'http://www.netmanagers.com.ar'
source 'https://github.com/netmanagers/puppet-ddclient'
summary 'Puppet module for ddclient'
description 'This module installs and manages ddclient. Check README for details.'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/concat', '>=1.0.0'
dependency 'example42/puppi',   '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
